language: java
jdk:
  - oraclejdk8
script: 
	- javac -cp junit4-4.12.jar:. SimpleTestSuite.java
	- java -cp .:junit4-4.12.jar:hamcrest-all-1.1.jar org.junit.runner.JUnitCore src/test/SimpleTestSuite
